spring:
  datasource:
    url: ${DATA_URI}
    username: ${DATA_USERNAME}
    password: ${DATA_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

clova:
  search-url: ${CLOVA_SEARCH_URL}
  content-url: ${CLOVA_CONTENT_URL}
  api-key: ${CLOVA_API_KEY}
  request-id: ${CLOVA_REQUEST_ID}