spring:
  web:
    resources:
      add-mappings: false
  datasource:
    hikari:
      data-source-properties:
        prepareThreshold: 0
        preferQueryMode: simple
      maximum-pool-size: 15
    url: ${DATA_URI}
    username: ${DATA_USERNAME}
    password: ${DATA_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

clova:
  search-url: ${CLOVA_SEARCH_URL}
  content-url: ${CLOVA_CONTENT_URL}
  api-key: ${CLOVA_API_KEY}
  request-id: ${CLOVA_REQUEST_ID}

posthog:
  base-url: ${POSTHOG_BASE_URL}
  api-key: ${POSTHOG_API_KEY}

slack:
  url: ${SLACK_URL}